#!/usr/bin/env bash

sudo sh -c 'echo "deb http://52.41.5.107 trusty main" > /etc/apt/sources.list.d/head.list'
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net --recv-key 0xB01FA116
sudo add-apt-repository -y ppa:irie/blender                                
sudo apt-get update
sudo apt-get install head
