HR_CACHE=~/.hr/cache
HR_BUILD_ENVFILE=~/.hr/build_env.sh

MANYEARSLIB_PREFIX=${HR_PREFIX}/manyears
VISION_TOOL_PREFIX=${HR_PREFIX}/vision
DLIB_PATH=${VISION_TOOL_PREFIX}/dlib
TORCH_DIR=$VISION_TOOL_PREFIX/torch
OPENFACE_DIR=$VISION_TOOL_PREFIX/openface
EMOTIME_DIR=$VISION_TOOL_PREFIX/emotime
CPPMT_DIR=$VISION_TOOL_PREFIX/CppMT
