HR_CACHE=~/.hr/cache
HR_BUILD_ENVFILE=~/.hr/build_env.sh

cat <<EOF >$HR_BUILD_ENVFILE
export MANYEARSLIB_PREFIX=${HR_PREFIX}/manyears
export VISION_TOOL_PREFIX=${HR_PREFIX}/vision
export DLIB_PATH=${VISION_TOOL_PREFIX}/dlib
export TORCH_DIR=$VISION_TOOL_PREFIX/torch
export OPENFACE_DIR=$VISION_TOOL_PREFIX/openface
export EMOTIME_DIR=$VISION_TOOL_PREFIX/emotime
export CPPMT_DIR=$VISION_TOOL_PREFIX/CppMT
EOF

source $HR_BUILD_ENVFILE
