export HR_CACHE=~/.hr/cache
export HR_BUILD_ENVFILE=~/.hr/build_env.sh
export HR_WORKSPACE=~/workspace/hansonrobotics
export HR_VERSION=0.1.0

export MANYEARSLIB_PREFIX=${HR_PREFIX}/manyears
export VISION_TOOL_PREFIX=${HR_PREFIX}/vision
export DLIB_PATH=/tmp/dlib
export TORCH_DIR=$VISION_TOOL_PREFIX/torch
export OPENFACE_DIR=$VISION_TOOL_PREFIX/openface
export EMOTIME_DIR=$VISION_TOOL_PREFIX/emotime
export CPPMT_DIR=$VISION_TOOL_PREFIX/CppMT
export LIBRARY_PATH=$LIBRARY_PATH:$CPPMT_DIR/lib:$EMOTIME_DIR/lib
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$CPPMT_DIR/include:$EMOTIME_DIR/include

cat <<EOF >$HR_BUILD_ENVFILE
export HR_CACHE=${HR_CACHE}
export HR_BUILD_ENVFILE=${HR_BUILD_ENVFILE}
export HR_WORKSPACE=${HR_WORKSPACE}
export MANYEARSLIB_PREFIX=${MANYEARSLIB_PREFIX}
export VISION_TOOL_PREFIX=${VISION_TOOL_PREFIX}
export DLIB_PATH=${DLIB_PATH}
export TORCH_DIR=${TORCH_DIR}
export OPENFACE_DIR=${OPENFACE_DIR}
export EMOTIME_DIR=${EMOTIME_DIR}
export CPPMT_DIR=${CPPMT_DIR}
export LIBRARY_PATH=${LIBRARY_PATH}
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}
EOF

source $HR_BUILD_ENVFILE
